# Generated by Django 3.0.5 on 2020-04-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_question_quiz_report_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
