# Generated by Django 3.0.5 on 2020-04-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200409_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
