# Generated by Django 3.0.5 on 2020-04-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200409_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='passing_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
