# Generated by Django 3.0.5 on 2020-04-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_report_passing_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(default=''),
        ),
    ]
